#!/bin/bash
#
# Unified Dashboard Update Script
# One command to sync and regenerate everything
#
# Usage:
#   ./update.sh              # Full update
#   ./update.sh --quick      # Skip binary metrics (faster)
#   ./update.sh --serve      # Update and start server
#   ./update.sh --dry-run    # Show what would be synced
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================"
echo "Dashboard Update Pipeline"
echo "========================================"
echo "Directory: $SCRIPT_DIR"
echo ""

# Parse arguments
DRY_RUN=""
QUICK=""
SERVE=""
PORT=8030

for arg in "$@"; do
    case $arg in
        --dry-run)
            DRY_RUN="--dry-run"
            ;;
        --quick)
            QUICK="--quick"
            ;;
        --serve)
            SERVE="yes"
            ;;
        --port=*)
            PORT="${arg#*=}"
            ;;
    esac
done

# Step 1: Sync all results
echo "Step 1/4: Syncing all results..."
if [ -n "$DRY_RUN" ]; then
    python3 scripts/sync_all_results.py --dry-run
    echo ""
    echo "DRY-RUN mode: No changes made. Remove --dry-run to apply."
    exit 0
else
    python3 scripts/sync_all_results.py
fi

# Step 2: Score binary classifiers
if [ -z "$QUICK" ]; then
    echo ""
    echo "Step 2/4: Scoring binary classifiers..."
    python3 scripts/score_binary_classifiers.py
else
    echo ""
    echo "Step 2/4: Skipping binary metrics (--quick mode)"
fi

# Step 3: Generate modules_data.js
echo ""
echo "Step 3/4: Generating modules_data.js..."
python3 -c "
import json
import yaml
from pathlib import Path
from datetime import datetime

PROJECT_DIR = Path('$SCRIPT_DIR')
DATA_DIR = PROJECT_DIR / 'data'
DASHBOARDS_DIR = PROJECT_DIR / 'dashboards'

# Load all data
progress_data = []
history_file = DATA_DIR / 'progress_history.yaml'
if history_file.exists():
    with open(history_file) as f:
        history = yaml.safe_load(f) or {}
    progress_data = history.get('runs', [])

suggestions_data = []
suggestions_file = DATA_DIR / 'improvement_suggestions.json'
if suggestions_file.exists():
    with open(suggestions_file) as f:
        suggestions_data = json.load(f)

applied_data = {}
applied_file = DATA_DIR / 'applied_improvements.yaml'
if applied_file.exists():
    with open(applied_file) as f:
        applied_data = yaml.safe_load(f) or {}

improvement_history = {}
ih_file = DATA_DIR / 'improvement_history.yaml'
if ih_file.exists():
    with open(ih_file) as f:
        improvement_history = yaml.safe_load(f) or {}

binary_metrics = {}
metrics_file = DASHBOARDS_DIR / 'binary_metrics.json'
if metrics_file.exists():
    with open(metrics_file) as f:
        binary_metrics = json.load(f)

# Generate JS
js_content = '''/**
 * Shared data for module dashboards
 * Auto-generated by update.sh
 * Generated: ''' + datetime.now().isoformat() + '''
 */

const progressData = ''' + json.dumps(progress_data, indent=2) + ''';

const suggestionsData = ''' + json.dumps(suggestions_data, indent=2) + ''';

const appliedData = ''' + json.dumps(applied_data, indent=2) + ''';

const improvementHistory = ''' + json.dumps(improvement_history, indent=2) + ''';

const MODULE_FOLDER_MAP = {
    'm01': 'M01_ExtractOwnBrandEntities',
    'm01a': 'M01A_ExtractOwnBrandVariations_PathB',
    'm01b': 'M01B_ExtractBrandRelatedTerms_PathB',
    'm02': 'M02_ClassifyOwnBrandKeywords',
    'm02b': 'M02B_ClassifyOwnBrandKeywords_PathB',
    'm04': 'M04_ClassifyCompetitorBrandKeywords',
    'm04b': 'M04B_ClassifyCompetitorBrandKeywords_PathB',
    'm05': 'M05_ClassifyNonBrandedKeywords',
    'm05b': 'M05B_ClassifyNonBrandedKeywords_PathB',
    'm06': 'M06_GenerateProductTypeTaxonomy',
    'm07': 'M07_ExtractProductAttributes',
    'm08': 'M08_AssignAttributeRanks',
    'm09': 'M09_IdentifyPrimaryIntendedUse',
    'm10': 'M10_ValidatePrimaryIntendedUse',
    'm11': 'M11_IdentifyHardConstraints',
    'm12': 'M12_HardConstraintViolationCheck',
    'm13': 'M13_ProductTypeCheck',
    'm14': 'M14_PrimaryUseCheckSameType',
    'm15': 'M15_SubstituteCheck',
    'm16': 'M16_ComplementaryCheck',
};

const binaryMetrics = ''' + json.dumps(binary_metrics, indent=2) + ''';
'''

output_file = DASHBOARDS_DIR / 'modules_data.js'
with open(output_file, 'w') as f:
    f.write(js_content)
print(f'  Generated {output_file}')
print(f'    - {len(progress_data)} progress runs')
print(f'    - {len(binary_metrics)} binary metrics')
"

# Step 4: Summary
echo ""
echo "========================================"
echo "Dashboard Update Complete!"
echo "========================================"
echo ""
echo "Data synced to: $SCRIPT_DIR/data/"
echo "Dashboard at:   $SCRIPT_DIR/dashboards/"
echo ""
echo "Open: http://localhost:$PORT/tracking_dashboard.html"
echo "      http://localhost:$PORT/modules/m01.html"

# Optionally start server
if [ -n "$SERVE" ]; then
    echo ""
    echo "Starting HTTP server on port $PORT..."
    cd dashboards
    python3 -m http.server $PORT
fi
