/**
 * M12B Multi-class metrics data
 * Auto-generated by score_multiclass.py
 * Generated: 2026-01-26T16:22:44.723305
 */

const m12bMetricsData = {
  classes: ["R", "N", "S", "C"],
  classNames: {"R": "Relevant", "N": "Not Relevant", "S": "Substitute", "C": "Complementary"},
  results: {
  "claude-sonnet-4-20250514": {
    "total": 441,
    "correct": 304,
    "accuracy": 68.9,
    "macro_f1": 59.5,
    "per_class": {
      "R": {
        "tp": 175,
        "fp": 18,
        "fn": 41,
        "precision": 90.7,
        "recall": 81.0,
        "f1": 85.6
      },
      "N": {
        "tp": 45,
        "fp": 10,
        "fn": 68,
        "precision": 81.8,
        "recall": 39.8,
        "f1": 53.6
      },
      "S": {
        "tp": 16,
        "fp": 44,
        "fn": 15,
        "precision": 26.7,
        "recall": 51.6,
        "f1": 35.2
      },
      "C": {
        "tp": 68,
        "fp": 65,
        "fn": 13,
        "precision": 51.1,
        "recall": 84.0,
        "f1": 63.6
      }
    },
    "confusion_matrix": {
      "R": {
        "R": 175,
        "N": 3,
        "S": 34,
        "C": 4
      },
      "N": {
        "R": 11,
        "N": 45,
        "S": 9,
        "C": 48
      },
      "S": {
        "R": 1,
        "N": 1,
        "S": 16,
        "C": 13
      },
      "C": {
        "R": 6,
        "N": 6,
        "S": 1,
        "C": 68
      }
    },
    "expected_distribution": {
      "R": 216,
      "N": 113,
      "S": 31,
      "C": 81
    },
    "actual_distribution": {
      "R": 193,
      "N": 55,
      "S": 60,
      "C": 133
    },
    "model": "claude-sonnet-4-20250514",
    "source_file": "M12B_V1_CombinedClassification_v1_260126_claudesonnet420250514.csv"
  },
  "gpt-5": {
    "total": 382,
    "correct": 275,
    "accuracy": 72.0,
    "macro_f1": 62.8,
    "per_class": {
      "R": {
        "tp": 152,
        "fp": 1,
        "fn": 47,
        "precision": 99.3,
        "recall": 76.4,
        "f1": 86.4
      },
      "N": {
        "tp": 64,
        "fp": 31,
        "fn": 30,
        "precision": 67.4,
        "recall": 68.1,
        "f1": 67.7
      },
      "S": {
        "tp": 13,
        "fp": 38,
        "fn": 17,
        "precision": 25.5,
        "recall": 43.3,
        "f1": 32.1
      },
      "C": {
        "tp": 46,
        "fp": 37,
        "fn": 13,
        "precision": 55.4,
        "recall": 78.0,
        "f1": 64.8
      }
    },
    "confusion_matrix": {
      "R": {
        "R": 152,
        "N": 10,
        "S": 31,
        "C": 6
      },
      "N": {
        "R": 0,
        "N": 64,
        "S": 7,
        "C": 23
      },
      "S": {
        "R": 0,
        "N": 9,
        "S": 13,
        "C": 8
      },
      "C": {
        "R": 1,
        "N": 12,
        "S": 0,
        "C": 46
      }
    },
    "expected_distribution": {
      "R": 199,
      "N": 94,
      "S": 30,
      "C": 59
    },
    "actual_distribution": {
      "R": 153,
      "N": 95,
      "S": 51,
      "C": 83
    },
    "model": "gpt-5",
    "source_file": "M12B_V1_CombinedClassification_v1_260126_gpt5.csv"
  },
  "gemini-2.0-flash": {
    "total": 442,
    "correct": 276,
    "accuracy": 62.4,
    "macro_f1": 53.1,
    "per_class": {
      "R": {
        "tp": 132,
        "fp": 8,
        "fn": 85,
        "precision": 94.3,
        "recall": 60.8,
        "f1": 73.9
      },
      "N": {
        "tp": 73,
        "fp": 79,
        "fn": 40,
        "precision": 48.0,
        "recall": 64.6,
        "f1": 55.1
      },
      "S": {
        "tp": 5,
        "fp": 7,
        "fn": 26,
        "precision": 41.7,
        "recall": 16.1,
        "f1": 23.3
      },
      "C": {
        "tp": 66,
        "fp": 72,
        "fn": 15,
        "precision": 47.8,
        "recall": 81.5,
        "f1": 60.3
      }
    },
    "confusion_matrix": {
      "R": {
        "R": 132,
        "N": 60,
        "S": 6,
        "C": 19
      },
      "N": {
        "R": 3,
        "N": 73,
        "S": 1,
        "C": 36
      },
      "S": {
        "R": 1,
        "N": 8,
        "S": 5,
        "C": 17
      },
      "C": {
        "R": 4,
        "N": 11,
        "S": 0,
        "C": 66
      }
    },
    "expected_distribution": {
      "R": 217,
      "N": 113,
      "S": 31,
      "C": 81
    },
    "actual_distribution": {
      "R": 140,
      "N": 152,
      "S": 12,
      "C": 138
    },
    "model": "gemini-2.0-flash",
    "source_file": "M12B_V1_CombinedClassification_v1_260126_gemini20flash.csv"
  },
  "gpt-4o-mini": {
    "total": 442,
    "correct": 246,
    "accuracy": 55.7,
    "macro_f1": 48.3,
    "per_class": {
      "R": {
        "tp": 137,
        "fp": 22,
        "fn": 80,
        "precision": 86.2,
        "recall": 63.1,
        "f1": 72.9
      },
      "N": {
        "tp": 44,
        "fp": 32,
        "fn": 69,
        "precision": 57.9,
        "recall": 38.9,
        "f1": 46.6
      },
      "S": {
        "tp": 13,
        "fp": 73,
        "fn": 18,
        "precision": 15.1,
        "recall": 41.9,
        "f1": 22.2
      },
      "C": {
        "tp": 52,
        "fp": 69,
        "fn": 29,
        "precision": 43.0,
        "recall": 64.2,
        "f1": 51.5
      }
    },
    "confusion_matrix": {
      "R": {
        "R": 137,
        "N": 23,
        "S": 31,
        "C": 26
      },
      "N": {
        "R": 11,
        "N": 44,
        "S": 30,
        "C": 28
      },
      "S": {
        "R": 1,
        "N": 2,
        "S": 13,
        "C": 15
      },
      "C": {
        "R": 10,
        "N": 7,
        "S": 12,
        "C": 52
      }
    },
    "expected_distribution": {
      "R": 217,
      "N": 113,
      "S": 31,
      "C": 81
    },
    "actual_distribution": {
      "R": 159,
      "N": 76,
      "S": 86,
      "C": 121
    },
    "model": "gpt-4o-mini",
    "source_file": "M12B_V1_CombinedClassification_v1_210126_gpt4omini.csv"
  }
}
};
