/**
 * Rubrics data for dashboard
 * Auto-generated by aggregate_rubrics.py
 * Generated: 2026-01-26T15:27:42.431897
 */

const rubricsData = {
  modules: {
  "m01a": {
    "rubrics": {
      "M01a_has_variations": {
        "criterion": "Variations Generated",
        "is_primary": true,
        "results": {
          "gpt-4o-mini": {
            "pass": 73,
            "fail": 7,
            "error": 0,
            "total": 80,
            "pass_rate": 91.2
          },
          "claude-sonnet-4": {
            "pass": 44,
            "fail": 6,
            "error": 0,
            "total": 50,
            "pass_rate": 88.0
          },
          "gemini-2.0-flash": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M01a_no_unrelated_terms": {
        "criterion": "No Unrelated Terms",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 12,
            "fail": 68,
            "error": 0,
            "total": 80,
            "pass_rate": 15.0
          },
          "claude-sonnet-4": {
            "pass": 3,
            "fail": 47,
            "error": 0,
            "total": 50,
            "pass_rate": 6.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          }
        }
      },
      "M01a_count_in_range": {
        "criterion": "8-12 Variations Generated",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 2,
            "fail": 78,
            "error": 0,
            "total": 80,
            "pass_rate": 2.5
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 50,
            "error": 0,
            "total": 50,
            "pass_rate": 0.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M01a_first_is_canonical": {
        "criterion": "First Item is Correct Spelling",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 59,
            "fail": 21,
            "error": 0,
            "total": 80,
            "pass_rate": 73.8
          },
          "claude-sonnet-4": {
            "pass": 39,
            "fail": 11,
            "error": 0,
            "total": 50,
            "pass_rate": 78.0
          },
          "gemini-2.0-flash": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m01b": {
    "rubrics": {
      "M01b_sub_brands_found": {
        "criterion": "Sub-brands Identified",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 16,
            "fail": 64,
            "error": 0,
            "total": 80,
            "pass_rate": 20.0
          },
          "gpt-5": {
            "pass": 10,
            "fail": 40,
            "error": 0,
            "total": 50,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 7,
            "fail": 43,
            "error": 0,
            "total": 50,
            "pass_rate": 14.0
          },
          "gemini-2.0-flash": {
            "pass": 3,
            "fail": 7,
            "error": 0,
            "total": 10,
            "pass_rate": 30.0
          }
        }
      },
      "M01b_no_universal_standards": {
        "criterion": "No Universal Standards as Brand-Specific",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 70,
            "fail": 10,
            "error": 0,
            "total": 80,
            "pass_rate": 87.5
          },
          "gpt-5": {
            "pass": 46,
            "fail": 4,
            "error": 0,
            "total": 50,
            "pass_rate": 92.0
          },
          "claude-sonnet-4": {
            "pass": 44,
            "fail": 6,
            "error": 0,
            "total": 50,
            "pass_rate": 88.0
          },
          "gemini-2.0-flash": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M01b_manufacturer_null_when_same": {
        "criterion": "Manufacturer Null When Same as Brand",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 65,
            "fail": 15,
            "error": 0,
            "total": 80,
            "pass_rate": 81.2
          },
          "gpt-5": {
            "pass": 40,
            "fail": 10,
            "error": 0,
            "total": 50,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 39,
            "fail": 11,
            "error": 0,
            "total": 50,
            "pass_rate": 78.0
          },
          "gemini-2.0-flash": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      },
      "M01b_searchable_standards_default_empty": {
        "criterion": "Searchable Standards Defaults to Empty",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 72,
            "fail": 8,
            "error": 0,
            "total": 80,
            "pass_rate": 90.0
          },
          "gpt-5": {
            "pass": 45,
            "fail": 5,
            "error": 0,
            "total": 50,
            "pass_rate": 90.0
          },
          "claude-sonnet-4": {
            "pass": 43,
            "fail": 7,
            "error": 0,
            "total": 50,
            "pass_rate": 86.0
          },
          "gemini-2.0-flash": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m01": {
    "rubrics": {
      "M01_brand_extracted": {
        "criterion": "Brand Extracted",
        "is_primary": true,
        "results": {
          "gpt-4o-mini": {
            "pass": 339,
            "fail": 167,
            "error": 0,
            "total": 506,
            "pass_rate": 67.0
          },
          "unknown": {
            "pass": 28,
            "fail": 22,
            "error": 0,
            "total": 50,
            "pass_rate": 56.0
          },
          "claude-sonnet-4": {
            "pass": 34,
            "fail": 16,
            "error": 0,
            "total": 50,
            "pass_rate": 68.0
          },
          "gpt-4o": {
            "pass": 164,
            "fail": 74,
            "error": 0,
            "total": 238,
            "pass_rate": 68.9
          },
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 91,
            "fail": 107,
            "error": 0,
            "total": 198,
            "pass_rate": 46.0
          }
        }
      },
      "M01_no_hallucination": {
        "criterion": "No Hallucinated Brand",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 260,
            "fail": 246,
            "error": 0,
            "total": 506,
            "pass_rate": 51.4
          },
          "unknown": {
            "pass": 7,
            "fail": 43,
            "error": 0,
            "total": 50,
            "pass_rate": 14.0
          },
          "claude-sonnet-4": {
            "pass": 21,
            "fail": 29,
            "error": 0,
            "total": 50,
            "pass_rate": 42.0
          },
          "gpt-4o": {
            "pass": 124,
            "fail": 114,
            "error": 0,
            "total": 238,
            "pass_rate": 52.1
          },
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 85,
            "fail": 113,
            "error": 0,
            "total": 198,
            "pass_rate": 42.9
          }
        }
      },
      "M01_no_product_words": {
        "criterion": "No Product Words in Brand",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 302,
            "fail": 204,
            "error": 0,
            "total": 506,
            "pass_rate": 59.7
          },
          "unknown": {
            "pass": 9,
            "fail": 41,
            "error": 0,
            "total": 50,
            "pass_rate": 18.0
          },
          "claude-sonnet-4": {
            "pass": 28,
            "fail": 22,
            "error": 0,
            "total": 50,
            "pass_rate": 56.0
          },
          "gpt-4o": {
            "pass": 138,
            "fail": 100,
            "error": 0,
            "total": 238,
            "pass_rate": 58.0
          },
          "gemini-2.0-flash": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          },
          "gpt-5": {
            "pass": 121,
            "fail": 77,
            "error": 0,
            "total": 198,
            "pass_rate": 61.1
          }
        }
      },
      "M01_amazon_test_applied": {
        "criterion": "Amazon Test Applied",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 188,
            "fail": 318,
            "error": 0,
            "total": 506,
            "pass_rate": 37.2
          },
          "unknown": {
            "pass": 9,
            "fail": 41,
            "error": 0,
            "total": 50,
            "pass_rate": 18.0
          },
          "claude-sonnet-4": {
            "pass": 15,
            "fail": 35,
            "error": 0,
            "total": 50,
            "pass_rate": 30.0
          },
          "gpt-4o": {
            "pass": 92,
            "fail": 146,
            "error": 0,
            "total": 238,
            "pass_rate": 38.7
          },
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 70,
            "fail": 128,
            "error": 0,
            "total": 198,
            "pass_rate": 35.4
          }
        }
      },
      "M01_no_duplicates": {
        "criterion": "No Duplicate Entities",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 150,
            "fail": 356,
            "error": 0,
            "total": 506,
            "pass_rate": 29.6
          },
          "unknown": {
            "pass": 0,
            "fail": 50,
            "error": 0,
            "total": 50,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 19,
            "fail": 31,
            "error": 0,
            "total": 50,
            "pass_rate": 38.0
          },
          "gpt-4o": {
            "pass": 103,
            "fail": 135,
            "error": 0,
            "total": 238,
            "pass_rate": 43.3
          },
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 116,
            "fail": 82,
            "error": 0,
            "total": 198,
            "pass_rate": 58.6
          }
        }
      }
    }
  },
  "m02b": {
    "rubrics": {
      "M02_correct_classification": {
        "criterion": "Correct OB/null Classification",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 29,
            "fail": 21,
            "error": 0,
            "total": 50,
            "pass_rate": 58.0
          },
          "gpt-5": {
            "pass": 43,
            "fail": 7,
            "error": 0,
            "total": 50,
            "pass_rate": 86.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_matched_term_valid": {
        "criterion": "Matched Term Exists in Variations",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 46,
            "fail": 4,
            "error": 0,
            "total": 50,
            "pass_rate": 92.0
          },
          "gpt-5": {
            "pass": 33,
            "fail": 17,
            "error": 0,
            "total": 50,
            "pass_rate": 66.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_word_boundary_correct": {
        "criterion": "Word Boundary Handling",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 20,
            "fail": 30,
            "error": 0,
            "total": 50,
            "pass_rate": 40.0
          },
          "gpt-5": {
            "pass": 29,
            "fail": 21,
            "error": 0,
            "total": 50,
            "pass_rate": 58.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_no_similar_brand_confusion": {
        "criterion": "No Similar Brand Confusion",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 48,
            "fail": 2,
            "error": 0,
            "total": 50,
            "pass_rate": 96.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_no_non_brand_patterns": {
        "criterion": "Non-Brand Patterns Rejected",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 19,
            "fail": 31,
            "error": 0,
            "total": 50,
            "pass_rate": 38.0
          },
          "gpt-5": {
            "pass": 22,
            "fail": 28,
            "error": 0,
            "total": 50,
            "pass_rate": 44.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_exact_character_match": {
        "criterion": "Exact Character Match Required",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 19,
            "fail": 31,
            "error": 0,
            "total": 50,
            "pass_rate": 38.0
          },
          "gpt-5": {
            "pass": 25,
            "fail": 25,
            "error": 0,
            "total": 50,
            "pass_rate": 50.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M02_match_type_correct": {
        "criterion": "Match Type Correctly Identified",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 24,
            "fail": 26,
            "error": 0,
            "total": 50,
            "pass_rate": 48.0
          },
          "gpt-5": {
            "pass": 30,
            "fail": 20,
            "error": 0,
            "total": 50,
            "pass_rate": 60.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m02": {
    "rubrics": {
      "M02_correct_classification": {
        "criterion": "Correct OB/null Classification",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 45,
            "fail": 5,
            "error": 0,
            "total": 50,
            "pass_rate": 90.0
          },
          "gpt-5": {
            "pass": 32,
            "fail": 18,
            "error": 0,
            "total": 50,
            "pass_rate": 64.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_matched_term_valid": {
        "criterion": "Matched Term Exists in Variations",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 31,
            "fail": 19,
            "error": 0,
            "total": 50,
            "pass_rate": 62.0
          },
          "gpt-5": {
            "pass": 33,
            "fail": 17,
            "error": 0,
            "total": 50,
            "pass_rate": 66.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_word_boundary_correct": {
        "criterion": "Word Boundary Handling",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 41,
            "fail": 9,
            "error": 0,
            "total": 50,
            "pass_rate": 82.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_no_similar_brand_confusion": {
        "criterion": "No Similar Brand Confusion",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 44,
            "fail": 6,
            "error": 0,
            "total": 50,
            "pass_rate": 88.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_no_non_brand_patterns": {
        "criterion": "Non-Brand Patterns Rejected",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 16,
            "fail": 34,
            "error": 0,
            "total": 50,
            "pass_rate": 32.0
          },
          "gpt-5": {
            "pass": 49,
            "fail": 1,
            "error": 0,
            "total": 50,
            "pass_rate": 98.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_exact_character_match": {
        "criterion": "Exact Character Match Required",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 45,
            "fail": 5,
            "error": 0,
            "total": 50,
            "pass_rate": 90.0
          },
          "gpt-5": {
            "pass": 43,
            "fail": 7,
            "error": 0,
            "total": 50,
            "pass_rate": 86.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M02_match_type_correct": {
        "criterion": "Match Type Correctly Identified",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 45,
            "fail": 5,
            "error": 0,
            "total": 50,
            "pass_rate": 90.0
          },
          "gpt-5": {
            "pass": 33,
            "fail": 17,
            "error": 0,
            "total": 50,
            "pass_rate": 66.0
          },
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m04b": {
    "rubrics": {
      "M04_correct_classification": {
        "criterion": "Correct CB/null Classification",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 39,
            "fail": 11,
            "error": 0,
            "total": 50,
            "pass_rate": 78.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          }
        }
      },
      "M04_own_brand_excluded": {
        "criterion": "Own Brand Excluded",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 37,
            "fail": 13,
            "error": 0,
            "total": 50,
            "pass_rate": 74.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M04_case_insensitive_matching": {
        "criterion": "Case Insensitive Matching",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 41,
            "fail": 9,
            "error": 0,
            "total": 50,
            "pass_rate": 82.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          }
        }
      },
      "M04_competitor_identified": {
        "criterion": "Competitor Correctly Identified",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 15,
            "fail": 35,
            "error": 0,
            "total": 50,
            "pass_rate": 30.0
          },
          "gpt-5": {
            "pass": 43,
            "fail": 7,
            "error": 0,
            "total": 50,
            "pass_rate": 86.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      }
    }
  },
  "m04": {
    "rubrics": {
      "M04_correct_classification": {
        "criterion": "Correct CB/null Classification",
        "is_primary": true,
        "results": {
          "gpt-4o-mini": {
            "pass": 14,
            "fail": 1,
            "error": 0,
            "total": 15,
            "pass_rate": 93.3
          },
          "gemini-2.0-flash": {
            "pass": 40,
            "fail": 10,
            "error": 0,
            "total": 50,
            "pass_rate": 80.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 10,
            "error": 0,
            "total": 15,
            "pass_rate": 33.3
          }
        }
      },
      "M04_own_brand_excluded": {
        "criterion": "Own Brand Excluded",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 13,
            "fail": 2,
            "error": 0,
            "total": 15,
            "pass_rate": 86.7
          },
          "gemini-2.0-flash": {
            "pass": 48,
            "fail": 2,
            "error": 0,
            "total": 50,
            "pass_rate": 96.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          }
        }
      },
      "M04_case_insensitive_matching": {
        "criterion": "Case Insensitive Matching",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          },
          "gemini-2.0-flash": {
            "pass": 42,
            "fail": 8,
            "error": 0,
            "total": 50,
            "pass_rate": 84.0
          },
          "gpt-5": {
            "pass": 50,
            "fail": 0,
            "error": 0,
            "total": 50,
            "pass_rate": 100.0
          },
          "gpt-4o": {
            "pass": 6,
            "fail": 9,
            "error": 0,
            "total": 15,
            "pass_rate": 40.0
          }
        }
      },
      "M04_competitor_identified": {
        "criterion": "Competitor Correctly Identified",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 15,
            "fail": 0,
            "error": 0,
            "total": 15,
            "pass_rate": 100.0
          },
          "gemini-2.0-flash": {
            "pass": 39,
            "fail": 11,
            "error": 0,
            "total": 50,
            "pass_rate": 78.0
          },
          "gpt-5": {
            "pass": 44,
            "fail": 6,
            "error": 0,
            "total": 50,
            "pass_rate": 88.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 5,
            "error": 0,
            "total": 15,
            "pass_rate": 66.7
          }
        }
      }
    }
  },
  "m05b": {
    "rubrics": {
      "M05_correct_classification": {
        "criterion": "Correct NB/null Classification",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 35,
            "fail": 15,
            "error": 0,
            "total": 50,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 45,
            "fail": 5,
            "error": 0,
            "total": 50,
            "pass_rate": 90.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      },
      "M05_hidden_brand_check": {
        "criterion": "Hidden Brand Awareness",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 13,
            "fail": 37,
            "error": 0,
            "total": 50,
            "pass_rate": 26.0
          },
          "gpt-5": {
            "pass": 11,
            "fail": 39,
            "error": 0,
            "total": 50,
            "pass_rate": 22.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      }
    }
  },
  "m05": {
    "rubrics": {
      "M05_correct_classification": {
        "criterion": "Correct NB/null Classification",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 35,
            "fail": 15,
            "error": 0,
            "total": 50,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 46,
            "fail": 4,
            "error": 0,
            "total": 50,
            "pass_rate": 92.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 0,
            "error": 0,
            "total": 2,
            "pass_rate": 100.0
          }
        }
      },
      "M05_hidden_brand_check": {
        "criterion": "Hidden Brand Awareness",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 23,
            "fail": 27,
            "error": 0,
            "total": 50,
            "pass_rate": 46.0
          },
          "gpt-5": {
            "pass": 8,
            "fail": 42,
            "error": 0,
            "total": 50,
            "pass_rate": 16.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 0,
            "error": 0,
            "total": 2,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m06": {
    "rubrics": {
      "M06_three_level_hierarchy": {
        "criterion": "Three-Level Hierarchy",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 1,
            "fail": 19,
            "error": 0,
            "total": 20,
            "pass_rate": 5.0
          },
          "gpt-4o-mini": {
            "pass": 0,
            "fail": 12,
            "error": 0,
            "total": 12,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 50,
            "error": 0,
            "total": 50,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 1,
            "fail": 19,
            "error": 0,
            "total": 20,
            "pass_rate": 5.0
          }
        }
      },
      "M06_product_type_focused": {
        "criterion": "Product Type Focused",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 18,
            "fail": 2,
            "error": 0,
            "total": 20,
            "pass_rate": 90.0
          },
          "gpt-4o-mini": {
            "pass": 10,
            "fail": 2,
            "error": 0,
            "total": 12,
            "pass_rate": 83.3
          },
          "gpt-5": {
            "pass": 18,
            "fail": 2,
            "error": 0,
            "total": 20,
            "pass_rate": 90.0
          },
          "claude-sonnet-4": {
            "pass": 44,
            "fail": 6,
            "error": 0,
            "total": 50,
            "pass_rate": 88.0
          },
          "gpt-4o": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          }
        }
      },
      "M06_hierarchy_correct": {
        "criterion": "Hierarchy Order Correct",
        "is_primary": true,
        "results": {
          "gemini-2.5-pro": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "gpt-4o-mini": {
            "pass": 0,
            "fail": 12,
            "error": 0,
            "total": 12,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 1,
            "fail": 19,
            "error": 0,
            "total": 20,
            "pass_rate": 5.0
          },
          "claude-sonnet-4": {
            "pass": 1,
            "fail": 49,
            "error": 0,
            "total": 50,
            "pass_rate": 2.0
          },
          "gpt-4o": {
            "pass": 12,
            "fail": 8,
            "error": 0,
            "total": 20,
            "pass_rate": 60.0
          }
        }
      },
      "M06_product_type_accurate": {
        "criterion": "Product Type Accurate",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "gpt-4o-mini": {
            "pass": 11,
            "fail": 1,
            "error": 0,
            "total": 12,
            "pass_rate": 91.7
          },
          "gpt-5": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "claude-sonnet-4": {
            "pass": 49,
            "fail": 1,
            "error": 0,
            "total": 50,
            "pass_rate": 98.0
          },
          "gpt-4o": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          }
        }
      },
      "M06_max_three_levels": {
        "criterion": "Maximum Three Levels",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 11,
            "fail": 9,
            "error": 0,
            "total": 20,
            "pass_rate": 55.0
          },
          "gpt-4o-mini": {
            "pass": 7,
            "fail": 5,
            "error": 0,
            "total": 12,
            "pass_rate": 58.3
          },
          "gpt-5": {
            "pass": 12,
            "fail": 8,
            "error": 0,
            "total": 20,
            "pass_rate": 60.0
          },
          "claude-sonnet-4": {
            "pass": 33,
            "fail": 17,
            "error": 0,
            "total": 50,
            "pass_rate": 66.0
          },
          "gpt-4o": {
            "pass": 19,
            "fail": 1,
            "error": 0,
            "total": 20,
            "pass_rate": 95.0
          }
        }
      },
      "M06_no_material_feature_levels": {
        "criterion": "No Material/Feature as Separate Levels",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 4,
            "fail": 16,
            "error": 0,
            "total": 20,
            "pass_rate": 20.0
          },
          "gpt-4o-mini": {
            "pass": 3,
            "fail": 9,
            "error": 0,
            "total": 12,
            "pass_rate": 25.0
          },
          "gpt-5": {
            "pass": 4,
            "fail": 16,
            "error": 0,
            "total": 20,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 10,
            "fail": 40,
            "error": 0,
            "total": 50,
            "pass_rate": 20.0
          },
          "gpt-4o": {
            "pass": 6,
            "fail": 14,
            "error": 0,
            "total": 20,
            "pass_rate": 30.0
          }
        }
      }
    }
  },
  "m07": {
    "rubrics": {
      "M07_attributes_from_listing": {
        "criterion": "Attributes From Listing",
        "is_primary": true,
        "results": {
          "gemini-2.5-pro": {
            "pass": 5,
            "fail": 35,
            "error": 0,
            "total": 40,
            "pass_rate": 12.5
          },
          "gpt-4o-mini": {
            "pass": 2,
            "fail": 10,
            "error": 0,
            "total": 12,
            "pass_rate": 16.7
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 5,
            "fail": 25,
            "error": 0,
            "total": 30,
            "pass_rate": 16.7
          },
          "gpt-4o": {
            "pass": 16,
            "fail": 24,
            "error": 0,
            "total": 40,
            "pass_rate": 40.0
          }
        }
      },
      "M07_no_fabricated_use_cases": {
        "criterion": "No Fabricated Use Cases",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 38,
            "fail": 2,
            "error": 0,
            "total": 40,
            "pass_rate": 95.0
          },
          "gpt-4o-mini": {
            "pass": 12,
            "fail": 0,
            "error": 0,
            "total": 12,
            "pass_rate": 100.0
          },
          "claude-sonnet-4": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "gemini-2.0-flash": {
            "pass": 18,
            "fail": 2,
            "error": 0,
            "total": 20,
            "pass_rate": 90.0
          },
          "gpt-5": {
            "pass": 28,
            "fail": 2,
            "error": 0,
            "total": 30,
            "pass_rate": 93.3
          },
          "gpt-4o": {
            "pass": 38,
            "fail": 2,
            "error": 0,
            "total": 40,
            "pass_rate": 95.0
          }
        }
      },
      "M07_audiences_explicit_or_dash": {
        "criterion": "Audiences Explicit Only or Dash",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 14,
            "fail": 26,
            "error": 0,
            "total": 40,
            "pass_rate": 35.0
          },
          "gpt-4o-mini": {
            "pass": 7,
            "fail": 5,
            "error": 0,
            "total": 12,
            "pass_rate": 58.3
          },
          "claude-sonnet-4": {
            "pass": 14,
            "fail": 6,
            "error": 0,
            "total": 20,
            "pass_rate": 70.0
          },
          "gemini-2.0-flash": {
            "pass": 14,
            "fail": 6,
            "error": 0,
            "total": 20,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 18,
            "fail": 12,
            "error": 0,
            "total": 30,
            "pass_rate": 60.0
          },
          "gpt-4o": {
            "pass": 33,
            "fail": 7,
            "error": 0,
            "total": 40,
            "pass_rate": 82.5
          }
        }
      },
      "M07_specs_preserve_units": {
        "criterion": "Specifications Preserve Full Details",
        "is_primary": false,
        "results": {
          "gemini-2.5-pro": {
            "pass": 0,
            "fail": 40,
            "error": 0,
            "total": 40,
            "pass_rate": 0.0
          },
          "gpt-4o-mini": {
            "pass": 1,
            "fail": 11,
            "error": 0,
            "total": 12,
            "pass_rate": 8.3
          },
          "claude-sonnet-4": {
            "pass": 4,
            "fail": 16,
            "error": 0,
            "total": 20,
            "pass_rate": 20.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 4,
            "fail": 26,
            "error": 0,
            "total": 30,
            "pass_rate": 13.3
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 31,
            "error": 0,
            "total": 40,
            "pass_rate": 22.5
          }
        }
      }
    }
  },
  "m08": {
    "rubrics": {
      "M08_ranks_assigned": {
        "criterion": "Ranks Assigned",
        "is_primary": true,
        "results": {
          "unknown": {
            "pass": 1,
            "fail": 29,
            "error": 0,
            "total": 30,
            "pass_rate": 3.3
          },
          "gpt-4o-mini": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 6,
            "fail": 24,
            "error": 0,
            "total": 30,
            "pass_rate": 20.0
          }
        }
      },
      "M08_important_ranked_high": {
        "criterion": "Important Attributes Ranked High",
        "is_primary": false,
        "results": {
          "unknown": {
            "pass": 1,
            "fail": 29,
            "error": 0,
            "total": 30,
            "pass_rate": 3.3
          },
          "gpt-4o-mini": {
            "pass": 1,
            "fail": 9,
            "error": 0,
            "total": 10,
            "pass_rate": 10.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 25,
            "error": 0,
            "total": 30,
            "pass_rate": 16.7
          }
        }
      },
      "M08_unique_ranks_per_type": {
        "criterion": "Unique Ranks Per Type",
        "is_primary": false,
        "results": {
          "unknown": {
            "pass": 19,
            "fail": 11,
            "error": 0,
            "total": 30,
            "pass_rate": 63.3
          },
          "gpt-4o-mini": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          },
          "gemini-2.0-flash": {
            "pass": 1,
            "fail": 9,
            "error": 0,
            "total": 10,
            "pass_rate": 10.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 13,
            "fail": 17,
            "error": 0,
            "total": 30,
            "pass_rate": 43.3
          }
        }
      },
      "M08_title_attributes_ranked_high": {
        "criterion": "Title Attributes Ranked 1-2",
        "is_primary": false,
        "results": {
          "unknown": {
            "pass": 1,
            "fail": 29,
            "error": 0,
            "total": 30,
            "pass_rate": 3.3
          },
          "gpt-4o-mini": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 28,
            "error": 0,
            "total": 30,
            "pass_rate": 6.7
          }
        }
      }
    }
  },
  "m09": {
    "rubrics": {
      "M09_captures_core_purpose": {
        "criterion": "Captures Core Purpose",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "gpt-5": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "claude-sonnet-4": {
            "pass": 3,
            "fail": 7,
            "error": 0,
            "total": 10,
            "pass_rate": 30.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          }
        }
      },
      "M09_no_marketing_language": {
        "criterion": "No Marketing Language",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "gpt-5": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 3,
            "fail": 7,
            "error": 0,
            "total": 10,
            "pass_rate": 30.0
          },
          "gpt-4o": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          }
        }
      },
      "M09_word_count_3_to_6": {
        "criterion": "Word Count 3-6",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 1,
            "fail": 9,
            "error": 0,
            "total": 10,
            "pass_rate": 10.0
          },
          "gpt-5": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          }
        }
      },
      "M09_no_brand_tech_names": {
        "criterion": "No Brand or Technology Names",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "claude-sonnet-4": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          }
        }
      }
    }
  },
  "m10": {
    "rubrics": {
      "M10_invalid_correctly_flagged": {
        "criterion": "Invalid M09 Output Flagged",
        "is_primary": true,
        "results": {
          "gpt-5": {
            "pass": 9,
            "fail": 11,
            "error": 0,
            "total": 20,
            "pass_rate": 45.0
          },
          "gemini-2.0-flash": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "claude-sonnet-4": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          }
        }
      },
      "M10_fix_improves_output": {
        "criterion": "Fix Improves Output",
        "is_primary": false,
        "results": {
          "gpt-5": {
            "pass": 8,
            "fail": 12,
            "error": 0,
            "total": 20,
            "pass_rate": 40.0
          },
          "gemini-2.0-flash": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 4,
            "fail": 6,
            "error": 0,
            "total": 10,
            "pass_rate": 40.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          }
        }
      }
    }
  },
  "m11": {
    "rubrics": {
      "M11_constraint_count": {
        "criterion": "Constraint Count Reasonable",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          },
          "gpt-5": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          },
          "claude-sonnet-4": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          }
        }
      },
      "M11_constraints_non_negotiable": {
        "criterion": "Constraints Non-Negotiable",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          },
          "gpt-5": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          },
          "claude-sonnet-4": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          }
        }
      },
      "M11_only_true_constraints": {
        "criterion": "Only True Hard Constraints",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          },
          "claude-sonnet-4": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          },
          "gpt-4o": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          }
        }
      },
      "M11_critical_not_missed": {
        "criterion": "Critical Constraints Not Missed",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          }
        }
      },
      "M11_never_categories_excluded": {
        "criterion": "NEVER Categories Excluded",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          },
          "gpt-4o": {
            "pass": 5,
            "fail": 5,
            "error": 0,
            "total": 10,
            "pass_rate": 50.0
          }
        }
      },
      "M11_expected_distribution": {
        "criterion": "Expected 0-1 Hard Constraints",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 6,
            "fail": 4,
            "error": 0,
            "total": 10,
            "pass_rate": 60.0
          },
          "gpt-5": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          },
          "claude-sonnet-4": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          },
          "gpt-4o": {
            "pass": 7,
            "fail": 3,
            "error": 0,
            "total": 10,
            "pass_rate": 70.0
          }
        }
      },
      "M11_three_step_test_applied": {
        "criterion": "3-Step Test Applied",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-5": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 0,
            "fail": 10,
            "error": 0,
            "total": 10,
            "pass_rate": 0.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          }
        }
      }
    }
  },
  "m12b": {
    "rubrics": {
      "M12_correct_classification": {
        "criterion": "Correct R/S/C/N Label",
        "is_primary": true,
        "results": {
          "gpt-4o-mini": {
            "pass": 46,
            "fail": 24,
            "error": 0,
            "total": 70,
            "pass_rate": 65.7
          },
          "claude-sonnet-4": {
            "pass": 37,
            "fail": 13,
            "error": 0,
            "total": 50,
            "pass_rate": 74.0
          },
          "gemini-2.0-flash": {
            "pass": 34,
            "fail": 16,
            "error": 0,
            "total": 50,
            "pass_rate": 68.0
          },
          "gpt-5": {
            "pass": 40,
            "fail": 10,
            "error": 0,
            "total": 50,
            "pass_rate": 80.0
          }
        }
      },
      "M12_decision_path_followed": {
        "criterion": "Decision Path Followed",
        "is_primary": false,
        "results": {
          "gpt-4o-mini": {
            "pass": 18,
            "fail": 52,
            "error": 0,
            "total": 70,
            "pass_rate": 25.7
          },
          "claude-sonnet-4": {
            "pass": 18,
            "fail": 32,
            "error": 0,
            "total": 50,
            "pass_rate": 36.0
          },
          "gemini-2.0-flash": {
            "pass": 14,
            "fail": 36,
            "error": 0,
            "total": 50,
            "pass_rate": 28.0
          },
          "gpt-5": {
            "pass": 16,
            "fail": 34,
            "error": 0,
            "total": 50,
            "pass_rate": 32.0
          }
        }
      }
    }
  },
  "m12": {
    "rubrics": {
      "M12_correct_classification": {
        "criterion": "Correct R/S/C/N Label",
        "is_primary": true,
        "results": {
          "gpt-5": {
            "pass": 19,
            "fail": 1,
            "error": 0,
            "total": 20,
            "pass_rate": 95.0
          },
          "claude-sonnet-4": {
            "pass": 48,
            "fail": 2,
            "error": 0,
            "total": 50,
            "pass_rate": 96.0
          },
          "gemini-2.0-flash": {
            "pass": 49,
            "fail": 1,
            "error": 0,
            "total": 50,
            "pass_rate": 98.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M12_decision_path_followed": {
        "criterion": "Decision Path Followed",
        "is_primary": false,
        "results": {
          "gpt-5": {
            "pass": 0,
            "fail": 20,
            "error": 0,
            "total": 20,
            "pass_rate": 0.0
          },
          "claude-sonnet-4": {
            "pass": 14,
            "fail": 36,
            "error": 0,
            "total": 50,
            "pass_rate": 28.0
          },
          "gemini-2.0-flash": {
            "pass": 22,
            "fail": 28,
            "error": 0,
            "total": 50,
            "pass_rate": 44.0
          },
          "gpt-4o": {
            "pass": 2,
            "fail": 8,
            "error": 0,
            "total": 10,
            "pass_rate": 20.0
          }
        }
      }
    }
  },
  "m13": {
    "rubrics": {
      "M13_same_type_correct": {
        "criterion": "Same Type Answer Correct",
        "is_primary": true,
        "results": {
          "gpt-5": {
            "pass": 18,
            "fail": 2,
            "error": 0,
            "total": 20,
            "pass_rate": 90.0
          },
          "gemini-2.0-flash": {
            "pass": 17,
            "fail": 3,
            "error": 0,
            "total": 20,
            "pass_rate": 85.0
          },
          "claude-sonnet-4": {
            "pass": 38,
            "fail": 12,
            "error": 0,
            "total": 50,
            "pass_rate": 76.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M13_modifiers_stripped": {
        "criterion": "Modifiers Properly Stripped",
        "is_primary": false,
        "results": {
          "gpt-5": {
            "pass": 16,
            "fail": 4,
            "error": 0,
            "total": 20,
            "pass_rate": 80.0
          },
          "gemini-2.0-flash": {
            "pass": 15,
            "fail": 5,
            "error": 0,
            "total": 20,
            "pass_rate": 75.0
          },
          "claude-sonnet-4": {
            "pass": 35,
            "fail": 15,
            "error": 0,
            "total": 50,
            "pass_rate": 70.0
          },
          "gpt-4o": {
            "pass": 8,
            "fail": 2,
            "error": 0,
            "total": 10,
            "pass_rate": 80.0
          }
        }
      },
      "M13_synonyms_recognized": {
        "criterion": "Synonyms Recognized",
        "is_primary": false,
        "results": {
          "gpt-5": {
            "pass": 17,
            "fail": 3,
            "error": 0,
            "total": 20,
            "pass_rate": 85.0
          },
          "gemini-2.0-flash": {
            "pass": 19,
            "fail": 1,
            "error": 0,
            "total": 20,
            "pass_rate": 95.0
          },
          "claude-sonnet-4": {
            "pass": 36,
            "fail": 14,
            "error": 0,
            "total": 50,
            "pass_rate": 72.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      }
    }
  },
  "m14": {
    "rubrics": {
      "M14_same_use_correct": {
        "criterion": "Same Use Answer Correct",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "gpt-5": {
            "pass": 16,
            "fail": 4,
            "error": 0,
            "total": 20,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 47,
            "fail": 3,
            "error": 0,
            "total": 50,
            "pass_rate": 94.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M14_superficial_differences_ignored": {
        "criterion": "Superficial Differences Ignored",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "gpt-5": {
            "pass": 16,
            "fail": 4,
            "error": 0,
            "total": 20,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 47,
            "fail": 3,
            "error": 0,
            "total": 50,
            "pass_rate": 94.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M14_not_overly_cautious": {
        "criterion": "Not Overly Cautious",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 20,
            "fail": 0,
            "error": 0,
            "total": 20,
            "pass_rate": 100.0
          },
          "gpt-5": {
            "pass": 16,
            "fail": 4,
            "error": 0,
            "total": 20,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 47,
            "fail": 3,
            "error": 0,
            "total": 50,
            "pass_rate": 94.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m15": {
    "rubrics": {
      "M15_substitute_correct": {
        "criterion": "Substitute Answer Correct",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 10,
            "fail": 10,
            "error": 0,
            "total": 20,
            "pass_rate": 50.0
          },
          "gpt-5": {
            "pass": 15,
            "fail": 5,
            "error": 0,
            "total": 20,
            "pass_rate": 75.0
          },
          "claude-sonnet-4": {
            "pass": 10,
            "fail": 40,
            "error": 0,
            "total": 50,
            "pass_rate": 20.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      },
      "M15_sixty_percent_overlap": {
        "criterion": "60% Overlap Rule Applied",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 5,
            "fail": 15,
            "error": 0,
            "total": 20,
            "pass_rate": 25.0
          },
          "gpt-5": {
            "pass": 4,
            "fail": 16,
            "error": 0,
            "total": 20,
            "pass_rate": 20.0
          },
          "claude-sonnet-4": {
            "pass": 7,
            "fail": 43,
            "error": 0,
            "total": 50,
            "pass_rate": 14.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      }
    }
  },
  "m16": {
    "rubrics": {
      "M16_complementary_correct": {
        "criterion": "Complementary Answer Correct",
        "is_primary": true,
        "results": {
          "gemini-2.0-flash": {
            "pass": 14,
            "fail": 6,
            "error": 0,
            "total": 20,
            "pass_rate": 70.0
          },
          "gpt-5": {
            "pass": 11,
            "fail": 9,
            "error": 0,
            "total": 20,
            "pass_rate": 55.0
          },
          "claude-sonnet-4": {
            "pass": 38,
            "fail": 12,
            "error": 0,
            "total": 50,
            "pass_rate": 76.0
          },
          "gpt-4o": {
            "pass": 9,
            "fail": 1,
            "error": 0,
            "total": 10,
            "pass_rate": 90.0
          }
        }
      },
      "M16_amazon_bundle_test": {
        "criterion": "Amazon Bundle Test Applied",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 8,
            "fail": 12,
            "error": 0,
            "total": 20,
            "pass_rate": 40.0
          },
          "gpt-5": {
            "pass": 16,
            "fail": 4,
            "error": 0,
            "total": 20,
            "pass_rate": 80.0
          },
          "claude-sonnet-4": {
            "pass": 34,
            "fail": 16,
            "error": 0,
            "total": 50,
            "pass_rate": 68.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M16_same_category_not_complementary": {
        "criterion": "Same Category \u2260 Complementary",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 1,
            "fail": 19,
            "error": 0,
            "total": 20,
            "pass_rate": 5.0
          },
          "gpt-5": {
            "pass": 9,
            "fail": 11,
            "error": 0,
            "total": 20,
            "pass_rate": 45.0
          },
          "claude-sonnet-4": {
            "pass": 22,
            "fail": 28,
            "error": 0,
            "total": 50,
            "pass_rate": 44.0
          },
          "gpt-4o": {
            "pass": 10,
            "fail": 0,
            "error": 0,
            "total": 10,
            "pass_rate": 100.0
          }
        }
      },
      "M16_relationship_type_identified": {
        "criterion": "Relationship Type Identified",
        "is_primary": false,
        "results": {
          "gemini-2.0-flash": {
            "pass": 3,
            "fail": 17,
            "error": 0,
            "total": 20,
            "pass_rate": 15.0
          },
          "gpt-5": {
            "pass": 6,
            "fail": 14,
            "error": 0,
            "total": 20,
            "pass_rate": 30.0
          },
          "claude-sonnet-4": {
            "pass": 5,
            "fail": 45,
            "error": 0,
            "total": 50,
            "pass_rate": 10.0
          },
          "gpt-4o": {
            "pass": 1,
            "fail": 9,
            "error": 0,
            "total": 10,
            "pass_rate": 10.0
          }
        }
      }
    }
  }
},
  summary: {
  "total_modules": 21,
  "total_rubrics": 82,
  "primary_rubrics": 20,
  "secondary_rubrics": 62,
  "models": [
    "claude-sonnet-4",
    "gemini-2.0-flash",
    "gemini-2.5-pro",
    "gpt-4o",
    "gpt-4o-mini",
    "gpt-5",
    "unknown"
  ],
  "worst_rubrics": [
    {
      "module": "m08",
      "rubric_id": "M08_title_attributes_ranked_high",
      "criterion": "Title Attributes Ranked 1-2",
      "avg_pass_rate": 1.7,
      "is_primary": false
    },
    {
      "module": "m06",
      "rubric_id": "M06_three_level_hierarchy",
      "criterion": "Three-Level Hierarchy",
      "avg_pass_rate": 2.0,
      "is_primary": false
    },
    {
      "module": "m08",
      "rubric_id": "M08_ranks_assigned",
      "criterion": "Ranks Assigned",
      "avg_pass_rate": 3.9,
      "is_primary": true
    },
    {
      "module": "m08",
      "rubric_id": "M08_important_ranked_high",
      "criterion": "Important Attributes Ranked High",
      "avg_pass_rate": 5.0,
      "is_primary": false
    },
    {
      "module": "m11",
      "rubric_id": "M11_three_step_test_applied",
      "criterion": "3-Step Test Applied",
      "avg_pass_rate": 5.0,
      "is_primary": false
    },
    {
      "module": "m07",
      "rubric_id": "M07_specs_preserve_units",
      "criterion": "Specifications Preserve Full Details",
      "avg_pass_rate": 10.7,
      "is_primary": false
    },
    {
      "module": "m06",
      "rubric_id": "M06_hierarchy_correct",
      "criterion": "Hierarchy Order Correct",
      "avg_pass_rate": 13.4,
      "is_primary": true
    },
    {
      "module": "m07",
      "rubric_id": "M07_attributes_from_listing",
      "criterion": "Attributes From Listing",
      "avg_pass_rate": 14.3,
      "is_primary": true
    },
    {
      "module": "m01a",
      "rubric_id": "M01a_no_unrelated_terms",
      "criterion": "No Unrelated Terms",
      "avg_pass_rate": 15.2,
      "is_primary": false
    },
    {
      "module": "m16",
      "rubric_id": "M16_relationship_type_identified",
      "criterion": "Relationship Type Identified",
      "avg_pass_rate": 16.2,
      "is_primary": false
    },
    {
      "module": "m11",
      "rubric_id": "M11_critical_not_missed",
      "criterion": "Critical Constraints Not Missed",
      "avg_pass_rate": 17.5,
      "is_primary": true
    },
    {
      "module": "m01b",
      "rubric_id": "M01b_sub_brands_found",
      "criterion": "Sub-brands Identified",
      "avg_pass_rate": 21.0,
      "is_primary": false
    },
    {
      "module": "m08",
      "rubric_id": "M08_unique_ranks_per_type",
      "criterion": "Unique Ranks Per Type",
      "avg_pass_rate": 22.8,
      "is_primary": false
    },
    {
      "module": "m06",
      "rubric_id": "M06_no_material_feature_levels",
      "criterion": "No Material/Feature as Separate Levels",
      "avg_pass_rate": 23.0,
      "is_primary": false
    },
    {
      "module": "m12",
      "rubric_id": "M12_decision_path_followed",
      "criterion": "Decision Path Followed",
      "avg_pass_rate": 23.0,
      "is_primary": false
    },
    {
      "module": "m01a",
      "rubric_id": "M01a_count_in_range",
      "criterion": "8-12 Variations Generated",
      "avg_pass_rate": 25.6,
      "is_primary": false
    },
    {
      "module": "m09",
      "rubric_id": "M09_word_count_3_to_6",
      "criterion": "Word Count 3-6",
      "avg_pass_rate": 27.5,
      "is_primary": false
    },
    {
      "module": "m10",
      "rubric_id": "M10_fix_improves_output",
      "criterion": "Fix Improves Output",
      "avg_pass_rate": 30.0,
      "is_primary": false
    },
    {
      "module": "m12b",
      "rubric_id": "M12_decision_path_followed",
      "criterion": "Decision Path Followed",
      "avg_pass_rate": 30.4,
      "is_primary": false
    },
    {
      "module": "m01",
      "rubric_id": "M01_amazon_test_applied",
      "criterion": "Amazon Test Applied",
      "avg_pass_rate": 34.9,
      "is_primary": false
    }
  ],
  "generated_at": "2026-01-26T15:27:42.431809"
}
};
